start.html

Added hyperlinks for eAccounts and Swings' instagram. Also edited the text for hyperlinks a little.

Added new hyperlinks

---

CSScode.css
start.html

Edited the about section text and added it to the navigation bar. Also slightly edited the text under the menu section.

Revised About Section

---

about.html
start.html

Added an about page separate from the landing page and connected it from the nav bar

About Page

---

CSScode.css
about.html
start.html

Added different iframe for google maps map with pins for each on campus dining locations

Add new iframe

---

CSScode.css
about.html
start.html
verifyLogin.php

made changes in start.html, about.html, css file, and verifyLogin.php to redirect landing and about pages to index.php through a button and the navbar. altered the formatting in css so that the <a> Start</a> in start.html looked like a button instead of a link

start.html and about.html point to index.php through "Start"

---

about2.php
index.php
reviews.php
start2.php

Added the ability for users to post reviews.

106 add review posting

---

CSScode.css
Edit.php
reviews.php
uploadreview.php
write.php

Made edits to review format, navbar, and general format

Made visual edits

---

write.php

changed the write.php to include the SQL query of menu items

changed the write.php

---

Edit.php
delete.php
editrev.php
reviews.php
write.php

went through every php file and made sure to include the proper parameterizations of calls of SQL data

parameterized

---

reviews.php

updated reviews page so that its the only page that shows reviews and there is an option to display only your reviews or all reviews

update reviews page

---

Edit.php
about2.php
demo.php
start2.php

Created a budget demo.php and added it to the navbar of the other php pages

Added a budget demo

---

Controller/Api/BaseController.php
Controller/Api/UserController.php
Model/Database.php
Model/UserModel.php
inc/bootstrap.php
inc/config.php
index2.php

added rest api

---

Model/UserModel.php
budget/App.js

included card and username containers, also changed data to reflect the reviews data table instead of menu items

changed code to fit reviews page

---

budget/App.js

changed the reviews to show a certain number of icons out of 10 icon outlines. also added icons to navbar for home and reviews. the filled icon is displayed if the tab is selected and the outline is displayed if it isn't selected.

icons to navbar + rating

---

budget/App.js

added buttons to every review

---

Controller/Api/UserController.php
Model/UserModel.php
budget/App.js

added an edit feature to the edit button so the user can alter a review (rating can only be between 1-10 and user can only alter their own review)

added edit feature

---

Edit.php
write.php

Changed the navbars of Edit.php and write.php to include the new Ratings.php (not included in the home and about pages on purpose)

196 update navbars from editphp and writephp

---

reviews.php
uploadreview.php
write.php

Adds the ability to have a written review of the food item when writing reviews

198 add written review

---

CSScode.css
Edit.php
write.php

changed the write.php and edit.php files to be more consistent and clean. Had to do some HTML styling because CSS sheet wasn't responding.

edited format of write.php and edit.php files

---

Edit.php
Ratings.php
addcomment.php
comment.php
reviews.php
write.php

Added two php pages, one to allow the users to comment on reviews, another that controls the commenting backend

205 add comments

---

CSScode.css
Edit.php
Ratings.php
addcomment.php
comment.php
reviews.php
write.php

The comment branch doesn't actually have the comment.php because it isn't updated with the latest merge, so merge it with main to edit the comment.php

pull main into comment

---

Edit.php
comment.php
reviews.php

Buttons for comment were added to all reviews. Buttons for edit/delete were added only when the user presses the my reviews button

213 comment edit delete buttons

---

demo.php
update_history.php

demo updates with sql table purchases and purchases table updates with demo. Additionally the users table is now updated with current remaining balance so when the user logs in, the demo page already has their current budget info

fixed up demo and backend

---

demo.php
update_history.php

Allowed ability to manually edit the budget and amount spent. Also added some extra debugging lines through GPT because there was a calculation error that was crashing the page.

manual updates to budget

---

reviews.php
write.php

Made each part of the review only appear once per review

224 fix double review bug

---

demo.php
update_budget.php

added locations prompt in the demo so that location can be tracked in purchase table

added locations

---

personal_stats

each graph can now be looked at by month

added month tracker

---

demo.php
personal_stats
update_budget.php
update_history.php

some bug fixes, mostly allowing manual changes but also in displaying the month in personal stats, updating sql table, etc.

bug fix for manually changing budget/amount spent
